services:
  go: &go
    env_file: .env
    tty: true
    stdin_open: true
    build:
      context: .
    entrypoint: go
    command: help
    volumes:
      - .:/usr/src/app:delegated
      - gomod:/go/pkg/mod
      - ${LOCAL_DEP_PATH:-..}:/local

  app:
    <<: *go
    command: run ./server.go
    ports:
      - ${PORT}:${PORT}

  gen:
    <<: *go
    command: run github.com/99designs/gqlgen

  # https://github.com/EventStore/EventStore/blob/master/samples/server/docker-compose.yaml
  # https://developers.eventstore.com/server/v21.10/installation.html#use-docker-compose
  eventstore.db:
    env_file: .env
    image: ghcr.io/eventstore/eventstore:21.10.1-alpha-arm64v8
    ports:
      - ${EVENTSTORE_EXT_TCP_PORT}:${EVENTSTORE_EXT_TCP_PORT}
      - ${EVENTSTORE_HTTP_PORT}:${EVENTSTORE_HTTP_PORT}
    volumes:
      - eventstore-data:/var/lib/eventstore
      - eventstore-logs:/var/log/eventstore

volumes:
  gomod: {}
  eventstore-data: {}
  eventstore-logs: {}
